apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: chuaqiwang/nextjs-server:v1.0
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: next-js-secrets
                  key: DATABASE_URL
            - name: NEXTAUTH_URL
              valueFrom:
                secretKeyRef:
                  name: next-js-secrets
                  key: NEXTAUTH_URL
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: next-js-secrets
                  key: NEXTAUTH_SECRET
          securityContext:
            allowPrivilegeEscalation: false
